#!/usr/bin/env python3
"""
Build unified IconAid data files for PowerPoint VBA integration.

This script converts the unified icon catalog (10,724 icons) into a format
that VBA can use to render icons with:
- Customizable line color
- Customizable fill color  
- Customizable stroke width
- Consistent 24x24 proportional sizing

The icons are stored as SVG path data, which VBA converts to PowerPoint shapes.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = ROOT / "shared" / "iconaid" / "unified-catalog.json"
OUTPUT_DIR = ROOT / "apps" / "powerpoint" / "src"
JSON_OUTPUT = ROOT / "shared" / "iconaid" / "iconaid-ppt-data.json"

# Maximum icons per VBA module to stay under VBA limits
ICONS_PER_MODULE = 200


def load_catalog() -> dict:
    """Load the unified catalog."""
    with open(CATALOG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def simplify_path(path_d: str) -> str:
    """Simplify SVG path for VBA storage (remove extra whitespace)."""
    # Normalize whitespace
    path_d = " ".join(path_d.split())
    # Remove spaces around commands
    path_d = re.sub(r'\s*([MLHVCSQTAZ])\s*', r'\1', path_d, flags=re.IGNORECASE)
    # Add space between numbers where needed (for negative numbers)
    path_d = re.sub(r'(\d)-', r'\1 -', path_d)
    return path_d


def create_icon_record(icon: dict, index: int) -> dict:
    """Create a compact icon record for VBA."""
    # Combine all paths into one string, separated by |
    paths = icon.get("paths", icon.get("svg_paths", []))
    
    # Filter out empty/background paths
    filtered_paths = []
    for p in paths:
        p = p.strip()
        # Skip background rectangle paths
        if p.startswith("M0 0") and "H0" in p:
            continue
        if p.startswith("M0 0h24v24H0"):
            continue
        if not p:
            continue
        filtered_paths.append(simplify_path(p))
    
    # Build search text
    search_parts = [
        icon["name"].lower(),
        icon.get("category", "").lower(),
        " ".join(icon.get("tags", [])[:10]),
    ]
    search_text = " ".join(search_parts)
    
    return {
        "i": index,  # index
        "id": icon["id"],
        "n": icon["name"],  # name
        "c": icon.get("category", "General"),  # category
        "s": icon.get("source", ""),  # source
        "l": icon.get("license", "MIT"),  # license
        "p": filtered_paths,  # paths
        "t": search_text[:200],  # truncated search text
    }


def generate_vba_module(module_num: int, icons: list[dict]) -> str:
    """Generate a VBA module containing icon data."""
    lines = [
        f'Attribute VB_Name = "modIconData{module_num:02d}"',
        "' Generated by scripts/build_unified_iconaid.py",
        "' Part of the unified IconAid catalog with 10,724 icons",
        "Option Explicit",
        "",
        f"' Icons {icons[0]['i']} to {icons[-1]['i']} ({len(icons)} icons)",
        "",
        f"Public Function GetIconData{module_num:02d}(ByVal idx As Long) As String",
        "    Select Case idx",
    ]
    
    for icon in icons:
        # Escape paths for VBA string
        paths_str = "|".join(icon["p"])
        # Escape quotes
        paths_str = paths_str.replace('"', '""')
        
        # Format: index|id|name|category|paths
        record = f'{icon["id"]}|{icon["n"]}|{icon["c"]}|{paths_str}'
        
        # Truncate if too long for VBA
        if len(record) > 1000:
            # Keep only first few paths
            short_paths = icon["p"][:3]
            paths_str = "|".join(short_paths)
            record = f'{icon["id"]}|{icon["n"]}|{icon["c"]}|{paths_str}'
        
        lines.append(f'        Case {icon["i"]}: GetIconData{module_num:02d} = "{record}"')
    
    lines.extend([
        "    End Select",
        "End Function",
        "",
    ])
    
    return "\n".join(lines)


def generate_main_module(total_icons: int, num_modules: int, categories: list[str]) -> str:
    """Generate the main IconAid VBA module."""
    
    # Build category list for VBA
    cat_items = ", ".join(f'"{c}"' for c in categories[:30])
    
    return f'''Attribute VB_Name = "modIconAidUnified"
' Generated by scripts/build_unified_iconaid.py
' Unified IconAid with {total_icons:,} icons from 5 open-source libraries
' All icons support customizable stroke color, fill color, and line width
Option Explicit

Private Const ICON_VIEWBOX As Single = 24
Private Const ICON_COUNT As Long = {total_icons}
Private Const MODULE_COUNT As Long = {num_modules}
Private Const ICONS_PER_MODULE As Long = {ICONS_PER_MODULE}

' Icon rendering settings
Public Type IconStyle
    StrokeColor As Long      ' Line color (RGB)
    FillColor As Long        ' Fill color (RGB, -1 for none)
    StrokeWidth As Single    ' Line width in points (1.0 to 4.0)
    Size As Single           ' Icon size in points
End Type

' Default style
Public Function DefaultIconStyle() As IconStyle
    Dim style As IconStyle
    style.StrokeColor = RGB(31, 41, 55)  ' Dark gray
    style.FillColor = -1                  ' No fill
    style.StrokeWidth = 1.5               ' 1.5pt stroke
    style.Size = 24                       ' 24pt size
    DefaultIconStyle = style
End Function

' Get total icon count
Public Function GetIconCount() As Long
    GetIconCount = ICON_COUNT
End Function

' Get icon data by index
Public Function GetIconDataByIndex(ByVal idx As Long) As String
    If idx < 1 Or idx > ICON_COUNT Then
        GetIconDataByIndex = ""
        Exit Function
    End If
    
    Dim moduleNum As Long
    moduleNum = ((idx - 1) \\ ICONS_PER_MODULE) + 1
    
    Select Case moduleNum
        Case 1: GetIconDataByIndex = GetIconData01(idx)
        Case 2: GetIconDataByIndex = GetIconData02(idx)
        Case 3: GetIconDataByIndex = GetIconData03(idx)
        Case 4: GetIconDataByIndex = GetIconData04(idx)
        Case 5: GetIconDataByIndex = GetIconData05(idx)
        Case 6: GetIconDataByIndex = GetIconData06(idx)
        Case 7: GetIconDataByIndex = GetIconData07(idx)
        Case 8: GetIconDataByIndex = GetIconData08(idx)
        Case 9: GetIconDataByIndex = GetIconData09(idx)
        Case 10: GetIconDataByIndex = GetIconData10(idx)
        Case 11: GetIconDataByIndex = GetIconData11(idx)
        Case 12: GetIconDataByIndex = GetIconData12(idx)
        Case 13: GetIconDataByIndex = GetIconData13(idx)
        Case 14: GetIconDataByIndex = GetIconData14(idx)
        Case 15: GetIconDataByIndex = GetIconData15(idx)
        Case 16: GetIconDataByIndex = GetIconData16(idx)
        Case 17: GetIconDataByIndex = GetIconData17(idx)
        Case 18: GetIconDataByIndex = GetIconData18(idx)
        Case 19: GetIconDataByIndex = GetIconData19(idx)
        Case 20: GetIconDataByIndex = GetIconData20(idx)
        Case 21: GetIconDataByIndex = GetIconData21(idx)
        Case 22: GetIconDataByIndex = GetIconData22(idx)
        Case 23: GetIconDataByIndex = GetIconData23(idx)
        Case 24: GetIconDataByIndex = GetIconData24(idx)
        Case 25: GetIconDataByIndex = GetIconData25(idx)
        Case 26: GetIconDataByIndex = GetIconData26(idx)
        Case 27: GetIconDataByIndex = GetIconData27(idx)
        Case 28: GetIconDataByIndex = GetIconData28(idx)
        Case 29: GetIconDataByIndex = GetIconData29(idx)
        Case 30: GetIconDataByIndex = GetIconData30(idx)
        Case 31: GetIconDataByIndex = GetIconData31(idx)
        Case 32: GetIconDataByIndex = GetIconData32(idx)
        Case 33: GetIconDataByIndex = GetIconData33(idx)
        Case 34: GetIconDataByIndex = GetIconData34(idx)
        Case 35: GetIconDataByIndex = GetIconData35(idx)
        Case 36: GetIconDataByIndex = GetIconData36(idx)
        Case 37: GetIconDataByIndex = GetIconData37(idx)
        Case 38: GetIconDataByIndex = GetIconData38(idx)
        Case 39: GetIconDataByIndex = GetIconData39(idx)
        Case 40: GetIconDataByIndex = GetIconData40(idx)
        Case 41: GetIconDataByIndex = GetIconData41(idx)
        Case 42: GetIconDataByIndex = GetIconData42(idx)
        Case 43: GetIconDataByIndex = GetIconData43(idx)
        Case 44: GetIconDataByIndex = GetIconData44(idx)
        Case 45: GetIconDataByIndex = GetIconData45(idx)
        Case 46: GetIconDataByIndex = GetIconData46(idx)
        Case 47: GetIconDataByIndex = GetIconData47(idx)
        Case 48: GetIconDataByIndex = GetIconData48(idx)
        Case 49: GetIconDataByIndex = GetIconData49(idx)
        Case 50: GetIconDataByIndex = GetIconData50(idx)
        Case 51: GetIconDataByIndex = GetIconData51(idx)
        Case 52: GetIconDataByIndex = GetIconData52(idx)
        Case 53: GetIconDataByIndex = GetIconData53(idx)
        Case 54: GetIconDataByIndex = GetIconData54(idx)
        Case Else: GetIconDataByIndex = ""
    End Select
End Function

' Search icons by text query
Public Function SearchIcons(ByVal query As String, Optional ByVal maxResults As Long = 50) As Collection
    Dim results As New Collection
    Dim i As Long
    Dim iconData As String
    Dim parts() As String
    Dim searchLower As String
    Dim queryLower As String
    
    queryLower = LCase(query)
    
    For i = 1 To ICON_COUNT
        If results.Count >= maxResults Then Exit For
        
        iconData = GetIconDataByIndex(i)
        If Len(iconData) > 0 Then
            parts = Split(iconData, "|")
            If UBound(parts) >= 2 Then
                searchLower = LCase(parts(0) & " " & parts(1) & " " & parts(2))
                If InStr(1, searchLower, queryLower, vbTextCompare) > 0 Then
                    results.Add i
                End If
            End If
        End If
    Next i
    
    Set SearchIcons = results
End Function

' Insert icon at current selection with specified style
Public Sub InsertIcon(ByVal iconIndex As Long, ByVal style As IconStyle)
    Dim iconData As String
    Dim parts() As String
    Dim pathData As String
    Dim paths() As String
    Dim i As Long
    Dim shp As Shape
    Dim grp As Shape
    Dim shapes As New Collection
    Dim sl As Slide
    Dim scale As Single
    Dim baseLeft As Single
    Dim baseTop As Single
    
    ' Get current slide
    On Error Resume Next
    Set sl = ActiveWindow.View.Slide
    On Error GoTo 0
    If sl Is Nothing Then
        MsgBox "Please select a slide first.", vbExclamation
        Exit Sub
    End If
    
    ' Get icon data
    iconData = GetIconDataByIndex(iconIndex)
    If Len(iconData) = 0 Then
        MsgBox "Icon not found.", vbExclamation
        Exit Sub
    End If
    
    ' Parse icon data: id|name|category|path1|path2|...
    parts = Split(iconData, "|")
    If UBound(parts) < 3 Then
        MsgBox "Invalid icon data.", vbExclamation
        Exit Sub
    End If
    
    ' Calculate position and scale
    scale = style.Size / ICON_VIEWBOX
    
    ' Center on slide or at selection
    On Error Resume Next
    baseLeft = ActiveWindow.Selection.ShapeRange(1).Left
    baseTop = ActiveWindow.Selection.ShapeRange(1).Top
    On Error GoTo 0
    
    If baseLeft = 0 And baseTop = 0 Then
        baseLeft = (sl.Master.Width - style.Size) / 2
        baseTop = (sl.Master.Height - style.Size) / 2
    End If
    
    ' Create shapes from paths
    For i = 3 To UBound(parts)
        pathData = parts(i)
        If Len(pathData) > 0 Then
            Set shp = CreateShapeFromPath(sl, pathData, baseLeft, baseTop, scale, style)
            If Not shp Is Nothing Then
                shapes.Add shp
            End If
        End If
    Next i
    
    ' Group shapes
    If shapes.Count > 1 Then
        Dim shpNames() As String
        ReDim shpNames(1 To shapes.Count)
        For i = 1 To shapes.Count
            shpNames(i) = shapes(i).Name
        Next i
        Set grp = sl.Shapes.Range(shpNames).Group
        grp.Name = "IconAid_" & parts(0)
    ElseIf shapes.Count = 1 Then
        shapes(1).Name = "IconAid_" & parts(0)
    End If
End Sub

' Create a shape from SVG path data
Private Function CreateShapeFromPath(ByVal sl As Slide, ByVal pathData As String, _
    ByVal baseLeft As Single, ByVal baseTop As Single, ByVal scale As Single, _
    ByVal style As IconStyle) As Shape
    
    Dim fb As FreeformBuilder
    Dim shp As Shape
    Dim commands() As String
    Dim i As Long
    Dim cmd As String
    Dim nums() As Single
    Dim curX As Single, curY As Single
    Dim startX As Single, startY As Single
    Dim isClosed As Boolean
    
    On Error GoTo ErrorHandler
    
    ' Parse path into commands and coordinates
    ' This is a simplified SVG path parser supporting M, L, H, V, C, Z commands
    
    curX = 0: curY = 0
    startX = 0: startY = 0
    isClosed = False
    
    ' Start freeform
    Set fb = Nothing
    
    Dim pos As Long
    Dim pathLen As Long
    Dim cmdChar As String
    Dim numStr As String
    Dim numList As Collection
    
    pathLen = Len(pathData)
    pos = 1
    
    Do While pos <= pathLen
        cmdChar = Mid(pathData, pos, 1)
        pos = pos + 1
        
        ' Skip whitespace
        Do While pos <= pathLen And Mid(pathData, pos, 1) = " "
            pos = pos + 1
        Loop
        
        ' Read numbers until next command
        Set numList = New Collection
        numStr = ""
        Do While pos <= pathLen
            Dim c As String
            c = Mid(pathData, pos, 1)
            If c Like "[A-Za-z]" Then Exit Do
            If c = "," Or c = " " Then
                If Len(numStr) > 0 Then
                    numList.Add CSng(numStr)
                    numStr = ""
                End If
            ElseIf c = "-" And Len(numStr) > 0 Then
                numList.Add CSng(numStr)
                numStr = c
            Else
                numStr = numStr & c
            End If
            pos = pos + 1
        Loop
        If Len(numStr) > 0 Then
            numList.Add CSng(numStr)
        End If
        
        ' Process command
        Select Case UCase(cmdChar)
            Case "M"  ' Move to
                If numList.Count >= 2 Then
                    curX = numList(1) * scale
                    curY = numList(2) * scale
                    startX = curX
                    startY = curY
                    If fb Is Nothing Then
                        Set fb = sl.Shapes.BuildFreeform(msoEditingAuto, baseLeft + curX, baseTop + curY)
                    End If
                End If
                
            Case "L"  ' Line to
                If Not fb Is Nothing And numList.Count >= 2 Then
                    curX = numList(1) * scale
                    curY = numList(2) * scale
                    fb.AddNodes msoSegmentLine, msoEditingAuto, baseLeft + curX, baseTop + curY
                End If
                
            Case "H"  ' Horizontal line
                If Not fb Is Nothing And numList.Count >= 1 Then
                    curX = numList(1) * scale
                    fb.AddNodes msoSegmentLine, msoEditingAuto, baseLeft + curX, baseTop + curY
                End If
                
            Case "V"  ' Vertical line
                If Not fb Is Nothing And numList.Count >= 1 Then
                    curY = numList(1) * scale
                    fb.AddNodes msoSegmentLine, msoEditingAuto, baseLeft + curX, baseTop + curY
                End If
                
            Case "C"  ' Cubic bezier
                If Not fb Is Nothing And numList.Count >= 6 Then
                    Dim x1 As Single, y1 As Single
                    Dim x2 As Single, y2 As Single
                    Dim x3 As Single, y3 As Single
                    x1 = numList(1) * scale
                    y1 = numList(2) * scale
                    x2 = numList(3) * scale
                    y2 = numList(4) * scale
                    x3 = numList(5) * scale
                    y3 = numList(6) * scale
                    fb.AddNodes msoSegmentCurve, msoEditingAuto, _
                        baseLeft + x1, baseTop + y1, _
                        baseLeft + x2, baseTop + y2, _
                        baseLeft + x3, baseTop + y3
                    curX = x3
                    curY = y3
                End If
                
            Case "Z"  ' Close path
                isClosed = True
                If Not fb Is Nothing Then
                    ' Close by connecting back to start
                    If Abs(curX - startX) > 0.1 Or Abs(curY - startY) > 0.1 Then
                        fb.AddNodes msoSegmentLine, msoEditingAuto, baseLeft + startX, baseTop + startY
                    End If
                End If
                
            Case "A"  ' Arc (simplified - convert to line for now)
                If Not fb Is Nothing And numList.Count >= 7 Then
                    curX = numList(6) * scale
                    curY = numList(7) * scale
                    fb.AddNodes msoSegmentLine, msoEditingAuto, baseLeft + curX, baseTop + curY
                End If
        End Select
    Loop
    
    ' Convert freeform to shape
    If Not fb Is Nothing Then
        Set shp = fb.ConvertToShape
        
        ' Apply style
        With shp.Line
            .Visible = msoTrue
            .ForeColor.RGB = style.StrokeColor
            .Weight = style.StrokeWidth
            .EndArrowheadStyle = msoArrowheadNone
            .BeginArrowheadStyle = msoArrowheadNone
        End With
        
        If style.FillColor >= 0 Then
            shp.Fill.Solid
            shp.Fill.ForeColor.RGB = style.FillColor
        Else
            shp.Fill.Visible = msoFalse
        End If
        
        Set CreateShapeFromPath = shp
    End If
    
    Exit Function
    
ErrorHandler:
    Set CreateShapeFromPath = Nothing
End Function

' Quick insert with default style
Public Sub QuickInsertIcon(ByVal iconIndex As Long)
    InsertIcon iconIndex, DefaultIconStyle()
End Sub

' Insert icon with custom colors
Public Sub InsertIconWithColors(ByVal iconIndex As Long, ByVal strokeColor As Long, _
    Optional ByVal fillColor As Long = -1, Optional ByVal strokeWidth As Single = 1.5, _
    Optional ByVal iconSize As Single = 48)
    
    Dim style As IconStyle
    style.StrokeColor = strokeColor
    style.FillColor = fillColor
    style.StrokeWidth = strokeWidth
    style.Size = iconSize
    
    InsertIcon iconIndex, style
End Sub

' Get available categories
Public Function GetCategories() As String()
    Dim cats(1 To 18) As String
    cats(1) = "Arrows"
    cats(2) = "Brand"
    cats(3) = "Business"
    cats(4) = "Communication"
    cats(5) = "Design"
    cats(6) = "Devices"
    cats(7) = "Document"
    cats(8) = "E-commerce"
    cats(9) = "Finance"
    cats(10) = "General"
    cats(11) = "Health"
    cats(12) = "Map"
    cats(13) = "Media"
    cats(14) = "Nature"
    cats(15) = "People"
    cats(16) = "Security"
    cats(17) = "System"
    cats(18) = "Technology"
    GetCategories = cats
End Function

' Show icon browser dialog (placeholder for UI)
Public Sub ShowIconBrowser()
    ' This would open a UserForm with search and category browsing
    ' For now, show a simple input dialog
    Dim query As String
    Dim results As Collection
    Dim i As Long
    Dim msg As String
    
    query = InputBox("Search for icons:" & vbCrLf & vbCrLf & _
        "Enter a search term (e.g., 'chart', 'mail', 'user')" & vbCrLf & _
        "Or enter an icon index number to insert directly.", _
        "IconAid - {total_icons:,} Icons Available")
    
    If Len(query) = 0 Then Exit Sub
    
    ' Check if it's a number (direct index)
    If IsNumeric(query) Then
        Dim style As IconStyle
        style = DefaultIconStyle()
        style.Size = 48
        InsertIcon CLng(query), style
        Exit Sub
    End If
    
    ' Search
    Set results = SearchIcons(query, 20)
    
    If results.Count = 0 Then
        MsgBox "No icons found for '" & query & "'", vbInformation
        Exit Sub
    End If
    
    ' Show results
    msg = "Found " & results.Count & " icons:" & vbCrLf & vbCrLf
    For i = 1 To results.Count
        Dim iconData As String
        Dim parts() As String
        iconData = GetIconDataByIndex(results(i))
        parts = Split(iconData, "|")
        If UBound(parts) >= 1 Then
            msg = msg & results(i) & ": " & parts(1) & " (" & parts(2) & ")" & vbCrLf
        End If
        If i >= 15 Then
            msg = msg & "..." & vbCrLf
            Exit For
        End If
    Next i
    
    msg = msg & vbCrLf & "Enter an index number to insert:"
    
    Dim idx As String
    idx = InputBox(msg, "IconAid Search Results")
    
    If IsNumeric(idx) Then
        Dim s As IconStyle
        s = DefaultIconStyle()
        s.Size = 48
        InsertIcon CLng(idx), s
    End If
End Sub
'''


def main():
    print("=" * 60)
    print("BUILDING UNIFIED ICONAID FOR POWERPOINT")
    print("=" * 60)
    
    # Load catalog
    print("\nLoading unified catalog...")
    catalog = load_catalog()
    icons = catalog["icons"]
    print(f"Total icons: {len(icons)}")
    
    # Create icon records
    print("\nCreating icon records...")
    records = []
    for i, icon in enumerate(icons, 1):
        record = create_icon_record(icon, i)
        if record["p"]:  # Only include icons with paths
            records.append(record)
    
    print(f"Icons with valid paths: {len(records)}")
    
    # Split into modules
    num_modules = (len(records) + ICONS_PER_MODULE - 1) // ICONS_PER_MODULE
    print(f"VBA modules needed: {num_modules}")
    
    # Generate VBA modules
    print("\nGenerating VBA modules...")
    for mod_num in range(1, num_modules + 1):
        start_idx = (mod_num - 1) * ICONS_PER_MODULE
        end_idx = min(start_idx + ICONS_PER_MODULE, len(records))
        module_icons = records[start_idx:end_idx]
        
        vba_code = generate_vba_module(mod_num, module_icons)
        output_path = OUTPUT_DIR / f"modIconData{mod_num:02d}.bas"
        output_path.write_text(vba_code, encoding="utf-8")
        print(f"  Generated {output_path.name} ({len(module_icons)} icons)")
    
    # Generate main module
    print("\nGenerating main module...")
    categories = catalog.get("categories", [])
    main_code = generate_main_module(len(records), num_modules, categories)
    main_path = OUTPUT_DIR / "modIconAidUnified.bas"
    main_path.write_text(main_code, encoding="utf-8")
    print(f"  Generated {main_path.name}")
    
    # Save JSON for other uses
    print("\nSaving JSON data...")
    json_data = {
        "totalIcons": len(records),
        "categories": categories,
        "icons": records,
    }
    with open(JSON_OUTPUT, "w", encoding="utf-8") as f:
        json.dump(json_data, f, indent=2)
    print(f"  Saved {JSON_OUTPUT}")
    
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(f"Total icons: {len(records):,}")
    print(f"VBA modules: {num_modules}")
    print(f"Categories: {len(categories)}")
    print("\nAll icons support:")
    print("  ✓ Customizable stroke color")
    print("  ✓ Customizable fill color")
    print("  ✓ Customizable stroke width")
    print("  ✓ Consistent 24×24 proportional sizing")
    print("  ✓ Works offline (all data embedded in VBA)")


if __name__ == "__main__":
    main()
