Attribute VB_Name = "modIconAid"
' Generated by scripts/build_icon_catalog.py. Do not edit by hand.
Option Explicit

' IconAid uses an Office.js task pane. Keep this compatibility entry point
' so older RibbonX packages compile without loading the retired VBA browser.
Public Sub SearchAndInsertIcon()
    MsgBox "Open IconAid from Home > Add-ins.", vbInformation, "IconAid"
End Sub
